version: "3"

services:
  frontend:
    build: ./frontend
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - api

  api:
    build: ./api
    restart: always
    ports:
      - 5555:5000
    depends_on:
      - db

  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_HOST: db,
      MYSQL_PORT: 3306,
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: time_db

  adminer:
    image: adminer:latest
    restart: always
    ports:
      - 8888:8080
    depends_on:
      - db
